/* Phase 4 item 3b — bind optimised images onto the harvested cards.
   Moves `[[IMG:hash]]` markers out of the stem and into the engine's `fig` field, which
   figHTML() renders inside `.figwrap` (already `width:100%`, so mobile-safe).

   A card whose stem points at an image that does NOT resolve is not silently cleaned up.
   It is flagged `figMissing`, and G11 refuses to ship it — a question that says "examine
   the figure above" with no figure is not a weaker card, it is an unanswerable one.

   Output: audit/harvested-bound.js + audit/bind-report.json. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const images = JSON.parse(fs.readFileSync(path.join(HERE, 'images-optimised.json'), 'utf8'));
const { HARVESTED } = await import(pathToFileURL(path.join(HERE, 'harvested.js')).href);

/* Any way a card can end up claiming there is a figure to look at. */
const EMBEDDED = /\[\[IMG:([0-9a-f]{16})\]\]/g;
const NAMED = /\[\[IMG:((?![0-9a-f]{16}\]\])[^\]]*)\]\]/g;
/* Bare `[[IMG]]` — no colon, no name — is what an external <img> with no alt text
   becomes. A pattern requiring the colon leaves these in the stem, so cards shipped
   reading "Identify the structures in the image below. [[IMG]]". */
const BARE = /\[\[IMG\]\]/g;
const PLACEHOLDER = /\[image not available offline\]/g;
const DEICTIC = /\b(figure|image|diagram|micrograph|photo|graph|picture)\b[^.]{0,40}\b(above|below|shown|here|following)\b|\b(above|below|shown)\b[^.]{0,25}\b(figure|image|diagram)\b|\blabell?ed\b|\bin the (image|figure|diagram)\b/i;

const walk = (v, fn) => Array.isArray(v) ? v.map(x => walk(x, fn))
  : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, k === 'ev' ? x : walk(x, fn)]))
  : typeof v === 'string' ? fn(v) : v;

const bound = [];
const report = { bound: 0, figMissing: [], noFigureNeeded: 0, multi: 0 };

for (const card of HARVESTED) {
  const json = JSON.stringify(card);
  const embedded = [...new Set([...json.matchAll(EMBEDDED)].map(m => m[1]))];
  const named = [...new Set([...json.matchAll(NAMED)].map(m => m[1]))];
  const hasPlaceholder = PLACEHOLDER.test(json);
  const bareCount = (json.match(BARE) || []).length;

  const resolved = embedded.filter(h => images[h]);
  const unresolved = [...embedded.filter(h => !images[h]), ...named,
                      ...Array(bareCount).fill('an unnamed external image')];

  /* strip every marker from the visible text; the figure moves to `fig` */
  let c = walk(card, s => s.replace(EMBEDDED, ' ').replace(NAMED, ' ').replace(BARE, ' ').replace(PLACEHOLDER, ' ')
    .replace(/\s{2,}/g, ' ').trim());

  if (resolved.length) {
    c.fig = resolved.map(h => `<img src="${images[h]}" alt="Figure from her quiz question">`).join('');
    c.figcap = `From ${card.ev.quiz} · ${card.ev.n}`;
    report.bound++;
    if (resolved.length > 1) report.multi++;
  }

  /* Two different failures, and conflating them loses good cards.

     DEPENDENT — the stem cannot be answered without the picture: "the structure
     labelled B", "shown in the image", "examine the figure above". These are
     unanswerable and must not ship.

     DECORATIVE — the card merely HAD an image. Her "Electogenics of the heart" match
     card pairs definitions to terms and reads perfectly without it. Holding it would
     discard a sound question over a missing decoration.

     Both are held by default, because shipping an unanswerable card is the worse error;
     but they are reported separately so the decorative ones can be released by a human
     in one pass instead of being silently binned. */
  const stem = [c.q, c.text].filter(Boolean).join(' ');
  const dependent = DEICTIC.test(stem);
  const hadImage = hasPlaceholder || unresolved.length > 0;
  if ((dependent || hadImage) && !c.fig) {
    c.figMissing = dependent
      ? 'the stem cannot be answered without a figure the pack does not have'
      : 'the source question carried an image that is not recoverable offline, but the card reads without it';
    c.figHold = dependent ? 'dependent' : 'decorative';
    report.figMissing.push({ quiz: card.ev.quiz, n: card.ev.n, type: card.type,
                             hold: c.figHold, why: c.figMissing, q: stem.slice(0, 90) });
  } else if (!c.fig) {
    report.noFigureNeeded++;
  }
  bound.push(c);
}

fs.writeFileSync(path.join(HERE, 'harvested-bound.js'),
  `/* GENERATED by audit/bind-images.mjs — do not edit by hand. */\nexport const BOUND = ${JSON.stringify(bound, null, 1)};\n`);
fs.writeFileSync(path.join(HERE, 'bind-report.json'), JSON.stringify(report, null, 1));

const payload = bound.filter(c => c.fig).reduce((n, c) => n + c.fig.length, 0);
console.log('══ IMAGE BINDING ═══════════════════════════════════');
console.log(`  ${bound.length} cards`);
console.log(`    ${report.bound} bound to a figure${report.multi ? ` (${report.multi} with more than one)` : ''}`);
console.log(`    ${report.noFigureNeeded} need no figure`);
const dep=report.figMissing.filter(f=>f.hold==='dependent');
const dec=report.figMissing.filter(f=>f.hold==='decorative');
console.log(`    ${dep.length} UNANSWERABLE without a figure — hard hold (G11)`);
console.log(`    ${dec.length} had a decorative image only — hold, but releasable on review`);
console.log(`  inlined payload: ${(payload / 1048576).toFixed(2)} MB of base64`);
if (report.figMissing.length) {
  console.log('\n  held:');
  for (const f of report.figMissing) console.log(`    [${f.type}] ${f.q}\n        ${f.why}`);
}
console.log('\nwrote audit/harvested-bound.js, bind-report.json');
