/* GENERATED by audit/build-rails.mjs from hs2-module1's LINKS. Do not hand-edit.
   154 relations from the Module 1 study hub, arranged into 46 rails as an
   edge-disjoint path cover: every relation rides exactly one rail. See build-rails.mjs
   for why these are their own tier and why they do NOT count toward focus-point coverage. */
export const RAILS = [
 {
  "type": "rail",
  "topic": "cvs-vessels",
  "tier": "rail",
  "from": "cvs1",
  "name": "Filtration — the arterial end",
  "beads": [
   "Pump action of the heart",
   "Hydrostatic pressure",
   "Arterial end of the capillary",
   "Filtration",
   "Interstitium"
  ],
  "verbs": [
   "generates",
   "is highest at the",
   "favours",
   "forces fluid from the blood vessel into the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-vessels",
  "tier": "rail",
  "from": "cvs1",
  "name": "Reabsorption — the venous end",
  "beads": [
   "Water leaving the capillary",
   "Oncotic pressure",
   "Venous end of the capillary",
   "Reabsorption",
   "Capillary"
  ],
  "verbs": [
   "leaves plasma proteins behind, raising",
   "is highest at the",
   "favours",
   "forces fluid from the interstitium back into the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-vessels",
  "tier": "rail",
  "from": "cvs1",
  "name": "Hypertension → oedema",
  "beads": [
   "Hypertension",
   "Hydrostatic pressure",
   "Interstitium",
   "Oedema"
  ],
  "verbs": [
   "raises",
   "when raised, forces more fluid into the",
   "accumulating fluid, becomes"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-vessels",
  "tier": "rail",
  "from": "cvs1",
  "name": "Hypoalbuminaemia → oedema",
  "beads": [
   "Hypoalbuminaemia",
   "Oncotic pressure",
   "Reabsorption",
   "Oedema"
  ],
  "verbs": [
   "lowers plasma protein and so lowers",
   "when too low, fails to drive",
   "when it fails, leaves fluid in the tissues as"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-vessels",
  "tier": "rail",
  "from": "cvs1",
  "name": "Dehydration → less filtration",
  "beads": [
   "Dehydration",
   "Hydrostatic pressure",
   "Interstitium"
  ],
  "verbs": [
   "lowers blood volume and so lowers",
   "when lowered, forces less fluid into the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-vessels",
  "tier": "rail",
  "from": "cvs1",
  "name": "Why the artery wall is thick",
  "beads": [
   "Artery",
   "Tunica media",
   "Vasoconstriction & vasodilation",
   "Peripheral resistance"
  ],
  "verbs": [
   "carries blood away from the heart at high pressure, so it has a thick",
   "is smooth muscle, which performs",
   "changes vessel diameter and so changes"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-vessels",
  "tier": "rail",
  "from": "cvs1",
  "name": "Why the capillary is one cell thick",
  "beads": [
   "Capillary",
   "Exchange",
   "Tissue perfusion",
   "Lethal"
  ],
  "verbs": [
   "is one endothelial cell thick, which allows",
   "of oxygen, nutrients and wastes maintains",
   "when inadequate to vital organs, may be"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-anat",
  "tier": "rail",
  "from": "cvs2",
  "name": "Blood flow through the heart",
  "beads": [
   "Superior vena cava",
   "Right atrium",
   "Tricuspid valve",
   "Right ventricle",
   "Pulmonary valve",
   "Pulmonary artery",
   "Lungs",
   "Pulmonary vein",
   "Left atrium",
   "Bicuspid (mitral) valve",
   "Left ventricle",
   "Aortic valve",
   "Aorta"
  ],
  "verbs": [
   "returns deoxygenated blood to the",
   "pushes blood through the",
   "opens into the",
   "ejects blood through the",
   "opens into the",
   "carries deoxygenated blood to the",
   "oxygenate the blood and return it via the",
   "delivers oxygenated blood to the",
   "pushes blood through the",
   "opens into the",
   "ejects blood through the",
   "opens into the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-anat",
  "tier": "rail",
  "from": "cvs2",
  "name": "Coronary circulation",
  "beads": [
   "Ascending aorta",
   "Coronary arteries",
   "Myocardium",
   "Coronary sinus",
   "Right atrium"
  ],
  "verbs": [
   "carries ostia that open into the",
   "supply the",
   "drains its used blood into the",
   "opens into the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-anat",
  "tier": "rail",
  "from": "cvs2",
  "name": "How the AV valves are held shut",
  "beads": [
   "Chordae tendineae",
   "Papillary muscle",
   "Heart wall"
  ],
  "verbs": [
   "stop the AV valve flaps opening the wrong way, being anchored by the",
   "anchors the chordae tendineae to the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-ecg",
  "tier": "rail",
  "from": "cvs3",
  "name": "The conduction pathway to the QRS",
  "beads": [
   "SA node",
   "AV node",
   "Bundle of His",
   "Bundle branches",
   "Purkinje fibres",
   "Ventricular myocardium",
   "QRS complex",
   "Stroke volume"
  ],
  "verbs": [
   "fires at ~70 b/min and passes the impulse on to the",
   "delays it, then passes it to the",
   "crosses the fibrous skeleton and divides into the",
   "carry the impulse out to the",
   "depolarise the",
   "depolarising, writes on the ECG the",
   "means the ventricles contract, ejecting the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-ecg",
  "tier": "rail",
  "from": "cvs3",
  "name": "The P wave",
  "beads": [
   "SA node",
   "P wave",
   "Contract"
  ],
  "verbs": [
   "depolarises the atria, which writes on the ECG the",
   "causes the atria to"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-ecg",
  "tier": "rail",
  "from": "cvs3",
  "name": "The T wave",
  "beads": [
   "Ventricular repolarisation",
   "T wave",
   "Relax"
  ],
  "verbs": [
   "writes on the ECG the",
   "causes the ventricles to"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-ecg",
  "tier": "rail",
  "from": "cvs3",
  "name": "Why the myocardium contracts as one",
  "beads": [
   "Intercalated discs",
   "Conductivity",
   "Wave"
  ],
  "verbs": [
   "hold gap junctions that let the impulse pass fibre to fibre, giving",
   "makes the myocardium contract as one coordinated"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-ecg",
  "tier": "rail",
  "from": "cvs3",
  "name": "CO = SV × HR, BP = CO × PR",
  "beads": [
   "Stroke volume",
   "Cardiac output",
   "Blood pressure"
  ],
  "verbs": [
   "multiplied by heart rate gives",
   "multiplied by peripheral resistance gives"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-bp",
  "tier": "rail",
  "from": "cvs4",
  "name": "Baroreflex — the cardiac arm",
  "beads": [
   "Low blood pressure",
   "Baroreceptors",
   "Medulla oblongata",
   "Cardio-acceleratory centre",
   "Cardiac output",
   "Blood pressure"
  ],
  "verbs": [
   "is detected by",
   "in the aortic arch and carotid sinus signal the",
   "stimulates the",
   "raises heart rate and force of contraction, raising",
   "multiplied by peripheral resistance restores"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-bp",
  "tier": "rail",
  "from": "cvs4",
  "name": "Baroreflex — the vessel arm",
  "beads": [
   "Medulla oblongata",
   "Vasomotor centre",
   "Peripheral resistance",
   "Blood pressure"
  ],
  "verbs": [
   "stimulates the",
   "constricts the blood vessels, raising",
   "multiplied by cardiac output restores"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-bp",
  "tier": "rail",
  "from": "cvs4",
  "name": "RAAS — the vasoconstriction arm",
  "beads": [
   "Low blood pressure",
   "Kidney",
   "Renin",
   "Angiotensin I",
   "Angiotensin II",
   "Peripheral resistance"
  ],
  "verbs": [
   "reduces blood flow to the",
   "releases the enzyme",
   "converts angiotensinogen from the liver into",
   "is converted by ACE in the lungs into",
   "causes vasoconstriction, raising"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-bp",
  "tier": "rail",
  "from": "cvs4",
  "name": "RAAS — the ADH arm",
  "beads": [
   "Angiotensin II",
   "ADH",
   "Blood volume",
   "Stroke volume",
   "Blood pressure"
  ],
  "verbs": [
   "makes the posterior pituitary release",
   "makes the collecting ducts porous so water is reabsorbed, raising",
   "stretches the vessels and fills the heart, raising",
   "multiplied by heart rate and peripheral resistance sets"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-bp",
  "tier": "rail",
  "from": "cvs4",
  "name": "RAAS — the aldosterone arm",
  "beads": [
   "Angiotensin II",
   "Aldosterone",
   "Blood volume"
  ],
  "verbs": [
   "makes the adrenal cortex release",
   "reabsorbs sodium, and water follows salt, raising"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-bp",
  "tier": "rail",
  "from": "cvs4",
  "name": "Direct renal control",
  "beads": [
   "Kidney",
   "Glomerular filtration rate",
   "Urine output",
   "Blood volume"
  ],
  "verbs": [
   "receiving less blood flow, lowers its",
   "when reduced, lowers",
   "when reduced, keeps fluid in the blood, raising"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-bp",
  "tier": "rail",
  "from": "cvs4",
  "name": "The chemoreflex",
  "beads": [
   "Rising CO₂, falling O₂ or falling pH",
   "Chemoreceptors in the carotid and aortic bodies",
   "Medulla oblongata"
  ],
  "verbs": [
   "is detected by",
   "signal the"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-output",
  "tier": "rail",
  "from": "shock",
  "name": "Why shock kills",
  "beads": [
   "Circulatory shock",
   "Tissue",
   "Oxygen",
   "Cell death",
   "Organ failure"
  ],
  "verbs": [
   "is inadequate blood flow to meet the needs of the",
   "left unperfused, is starved of",
   "starvation causes",
   "accumulates into"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-output",
  "tier": "rail",
  "from": "shock",
  "name": "Hypovolaemic shock",
  "beads": [
   "Hypovolaemic shock",
   "Stroke volume",
   "Cardiac output",
   "Blood pressure",
   "Circulatory shock"
  ],
  "verbs": [
   "loses fluid volume, lowering",
   "when reduced, lowers",
   "when reduced, lowers",
   "too low to perfuse the tissues, is"
  ]
 },
 {
  "type": "rail",
  "topic": "cvs-output",
  "tier": "rail",
  "from": "shock",
  "name": "Distributive shock",
  "beads": [
   "Distributive shock",
   "Peripheral resistance",
   "Blood pressure"
  ],
  "verbs": [
   "shifts fluid into the wrong compartment by extreme vasodilation, lowering",
   "when it collapses, lowers"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-anat",
  "tier": "rail",
  "from": "resp1",
  "name": "The pathway of air",
  "beads": [
   "Nasal cavity",
   "Pharynx",
   "Larynx",
   "Trachea",
   "Main bronchi",
   "Bronchioles",
   "Terminal bronchioles",
   "Respiratory bronchioles",
   "Alveolar ducts",
   "Alveoli"
  ],
  "verbs": [
   "filters, warms and moistens air, passing it to the",
   "passes air to the",
   "passes air to the",
   "branches at the carina into the",
   "divide down into",
   "narrow into",
   "lead on to",
   "open into",
   "open into"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-anat",
  "tier": "rail",
  "from": "resp1",
  "name": "Why the alveolus can exchange gas",
  "beads": [
   "Alveoli",
   "Respiratory membrane",
   "Simple diffusion"
  ],
  "verbs": [
   "are lined by type I pneumocytes, which form part of the",
   "is thin enough (0.5–1 µm) for"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-anat",
  "tier": "rail",
  "from": "resp1",
  "name": "Surfactant keeps the alveoli open",
  "beads": [
   "Type II pneumocytes",
   "Surfactant",
   "Alveoli"
  ],
  "verbs": [
   "secrete",
   "reduces surface tension and so keeps open the"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-anat",
  "tier": "rail",
  "from": "resp1",
  "name": "The muco-ciliary escalator",
  "beads": [
   "Goblet cells",
   "Muco-ciliary escalator",
   "Pharynx"
  ],
  "verbs": [
   "make mucus that traps dust, forming with the cilia the",
   "sweeps trapped particles upward toward the"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-anat",
  "tier": "rail",
  "from": "resp1",
  "name": "The cough reflex",
  "beads": [
   "Carina",
   "Cough reflex",
   "Trachealis"
  ],
  "verbs": [
   "is sensitive to particles and triggers the",
   "contracts the"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-mech",
  "tier": "rail",
  "from": "resp2",
  "name": "Quiet inspiration",
  "beads": [
   "Diaphragm and external intercostals",
   "Thoracic cavity",
   "Intrapleural pressure",
   "Intrapulmonary volume",
   "Intrapulmonary pressure",
   "Pressure gradient",
   "Inspiration"
  ],
  "verbs": [
   "contract, increasing the volume of the",
   "expands, and the lung follows it because of the negative",
   "being negative, makes the lung tissue follow, raising",
   "rising, lowers by Boyle's law the",
   "falling below atmospheric, creates a",
   "drives air in until the pressures equalise —"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-mech",
  "tier": "rail",
  "from": "resp2",
  "name": "Quiet expiration is passive",
  "beads": [
   "Elastic recoil",
   "Intrapulmonary volume",
   "Intrapulmonary pressure",
   "Expiration"
  ],
  "verbs": [
   "of the stretched lungs, as the inspiratory muscles relax, reduces",
   "falling, raises by Boyle's law the",
   "rising above atmospheric, drives air out —"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-mech",
  "tier": "rail",
  "from": "resp2",
  "name": "How a pneumothorax collapses a lung",
  "beads": [
   "Pneumothorax",
   "Intrapleural pressure",
   "Atelectasis"
  ],
  "verbs": [
   "puts air in the pleural cavity, destroying the negative",
   "once lost, uncouples the lung from the chest wall, causing"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-mech",
  "tier": "rail",
  "from": "resp2",
  "name": "External respiration",
  "beads": [
   "Partial pressure gradient",
   "Simple diffusion",
   "External respiration"
  ],
  "verbs": [
   "drives gases across the respiratory membrane by",
   "moves O₂ into the blood and CO₂ into the alveoli — this is"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-gas",
  "tier": "rail",
  "from": "resp3",
  "name": "CO₂ becomes bicarbonate",
  "beads": [
   "CO₂",
   "Carbonic acid",
   "Bicarbonate",
   "Transported CO₂"
  ],
  "verbs": [
   "enters the red cell, where carbonic anhydrase joins it to water to form",
   "dissociates into hydrogen ions and",
   "diffuses into the plasma, carrying about 70% of the"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-gas",
  "tier": "rail",
  "from": "resp3",
  "name": "Hyperventilation → alkalosis",
  "beads": [
   "Hyperventilation",
   "Hydrogen ions",
   "Blood pH",
   "Alkalosis"
  ],
  "verbs": [
   "blows off CO₂, driving the buffer left and using up",
   "falling in concentration, raise the",
   "above 7.45, is"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-gas",
  "tier": "rail",
  "from": "resp3",
  "name": "Hypoventilation → acidosis",
  "beads": [
   "Hypoventilation",
   "Hydrogen ions",
   "Blood pH",
   "Acidosis"
  ],
  "verbs": [
   "retains CO₂, driving the buffer right and producing more",
   "rising in concentration, lower the",
   "below 7.35, is"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-gas",
  "tier": "rail",
  "from": "resp3",
  "name": "Oxygen loading",
  "beads": [
   "Haemoglobin",
   "Oxyhaemoglobin",
   "Oxygen"
  ],
  "verbs": [
   "binds four oxygen molecules to become",
   "carries 98.5% of the blood's"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-gas",
  "tier": "rail",
  "from": "resp3",
  "name": "The Bohr effect — unloading",
  "beads": [
   "Bohr effect",
   "Haemoglobin",
   "Tissues"
  ],
  "verbs": [
   "in warm, acidic, CO₂-rich tissue lowers the oxygen affinity of",
   "with lowered affinity, releases its oxygen to the"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-gas",
  "tier": "rail",
  "from": "resp3",
  "name": "Compensating for metabolic acidosis",
  "beads": [
   "Ketoacidosis",
   "Chemoreceptors",
   "CO₂",
   "Hydrogen ions"
  ],
  "verbs": [
   "raises hydrogen ions and drops blood pH, which is picked up by",
   "call for faster breathing, which exhales more",
   "falling, lets hydrogen ions and bicarbonate recombine, consuming"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-control",
  "tier": "rail",
  "from": "resp4",
  "name": "Rhythm → diaphragm",
  "beads": [
   "Ventral respiratory group",
   "Phrenic nerve",
   "Diaphragm",
   "Inspiration"
  ],
  "verbs": [
   "is self-exciting and sets the basic rhythm, firing down the",
   "stimulates the",
   "contracting, increases thoracic volume and produces"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-control",
  "tier": "rail",
  "from": "resp4",
  "name": "Rhythm → intercostals",
  "beads": [
   "Ventral respiratory group",
   "Intercostal nerves",
   "External intercostal muscles",
   "Inspiration"
  ],
  "verbs": [
   "also fires down the",
   "stimulate the",
   "contracting, lift the ribcage and produce"
  ]
 },
 {
  "type": "rail",
  "topic": "resp-control",
  "tier": "rail",
  "from": "resp4",
  "name": "The strongest respiratory drive",
  "beads": [
   "Hypercapnia",
   "Inspiratory centre",
   "Breathing",
   "CO₂"
  ],
  "verbs": [
   "is the strongest stimulus, exciting the",
   "when excited, increases the rate and depth of",
   "increasing, blows off"
  ]
 },
 {
  "type": "rail",
  "topic": "lymph",
  "tier": "rail",
  "from": "lymph",
  "name": "Where lymph goes",
  "beads": [
   "Blood capillary",
   "Interstitium",
   "Lymphatic capillaries",
   "Collecting vessels",
   "Lymph nodes",
   "Lymphatic trunks",
   "Subclavian vein"
  ],
  "verbs": [
   "filters out more fluid than it reabsorbs, leaving the excess in the",
   "is drained by blind-ended",
   "feed into",
   "carry lymph through the",
   "filter it and pass it on to the",
   "join the thoracic and right lymphatic ducts, which empty into the"
  ]
 },
 {
  "type": "rail",
  "topic": "lymph",
  "tier": "rail",
  "from": "lymph",
  "name": "How the immune response is organised",
  "beads": [
   "Macrophages and B cells",
   "T cells",
   "Immune system"
  ],
  "verbs": [
   "collect antigens and present them to",
   "organise the"
  ]
 },
 {
  "type": "rail",
  "topic": "lymph",
  "tier": "rail",
  "from": "lymph",
  "name": "How lymphoedema happens",
  "beads": [
   "Obstruction of lymph flow",
   "Interstitium",
   "Lymphoedema"
  ],
  "verbs": [
   "stops the drainage of the",
   "accumulating fluid, becomes"
  ]
 }
];
