/* Ports figures from hs2-module1 into figs.js — BYTE FOR BYTE.
   House rule: reuse a proven surface by copying it exactly, never by
   re-describing it in prose. A spec always drifts; a copy plus a diff
   check does not.

     node port-figs.mjs          rebuild figs.js from hs2-module1
     node port-figs.mjs --check  fail if figs.js has drifted from source

   Figures are the AUTHORED SVGs and CC-BY OpenStax rasters already
   shipping in hs2-module1; nothing here is re-drawn. */
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = '../hs2-module1/index.html';

// which figures this pack uses, and the criterion each supports
export const WANTED = {
  'cvs1-walls':       'cvs-2',
  'cvs1-cap-exchange':'cvs-3',
  'cvs2-layers':      'cvs-5',
  'cvs2-valves':      'cvs-5',
  'cvs3-ecg':         'cvs-8',
  'cvs3-conduction':  'cvs-8',
  'cvs4-raas':        'cvs-12',
  'resp1-tract':      'resp-2',   // blind spot
  'resp1-pleura':     'resp-2',   // blind spot
  'resp1-alveolus':   'resp-5',
  'resp2-volumes':    'resp-6',
  'resp3-odc':        'resp-11',
  'lymph-node':       'cs-vacc',  // blind spot
  'lymph-ducts':      'lymph-3',
  'lymph-spleen':     'lymph-2',
};

function extract() {
  const s = readFileSync(SRC, 'utf8');
  const figStart = s.indexOf('const FIGS=');
  const figEnd = s.indexOf('const figsAll');
  const imgStart = s.indexOf('const IMGS=');
  if (figStart < 0 || figEnd < 0) throw new Error('FIGS block not found in ' + SRC);
  const figSeg = s.slice(figStart, figEnd);
  const imgSeg = imgStart >= 0 ? s.slice(imgStart) : '';

  // raster payloads, keyed by IMGS name
  const imgs = {};
  for (const m of imgSeg.matchAll(/'([a-z0-9-]+)'\s*:\s*'(data:image\/[^']+)'/g)) imgs[m[1]] = m[2];

  const out = {};
  for (const id of Object.keys(WANTED)) {
    const at = figSeg.indexOf(`{id:'${id}'`);
    if (at < 0) throw new Error(`figure "${id}" not found in hs2-module1 — did it get renamed upstream?`);
    // the figure object runs until the next {id:'…' or the end of the block
    const nextAt = figSeg.indexOf("{id:'", at + 5);
    const body = figSeg.slice(at, nextAt < 0 ? figSeg.length : nextAt);

    const cap = (body.match(/\bcap:\s*'((?:[^'\\]|\\.)*)'/) || [])[1] || '';
    const alt = (body.match(/\balt:\s*'((?:[^'\\]|\\.)*)'/) || [])[1] || '';

    let art = null, kind = null;
    const svgAt = body.indexOf('svg:`');
    if (svgAt >= 0) {
      const close = body.indexOf('`', svgAt + 5);
      if (close < 0) throw new Error(`unterminated svg literal in "${id}"`);
      art = body.slice(svgAt + 5, close);
      if (art.includes('${')) throw new Error(`"${id}" svg contains a template substitution — cannot be ported verbatim`);
      kind = 'svg';
    } else {
      const imgName = (body.match(/\bimg:\s*'([a-z0-9-]+)'/) || [])[1];
      if (!imgName || !imgs[imgName]) throw new Error(`"${id}" has neither an svg literal nor a resolvable img`);
      art = imgs[imgName];
      kind = 'img';
    }
    out[id] = { kind, art, cap, alt, crit: WANTED[id] };
  }
  return out;
}

function render(figs) {
  const body = Object.entries(figs).map(([id, f]) => {
    const art = f.kind === 'svg'
      ? '`' + f.art + '`'
      : `'<img src="${f.art}" alt="${f.alt.replace(/"/g, '&quot;')}"/>'`;
    return `  '${id}': { crit:'${f.crit}', cap:'${f.cap}',\n    art: ${art} },`;
  }).join('\n\n');
  return `/* GENERATED by port-figs.mjs — do not hand-edit.
   Figures copied byte for byte from hs2-module1/index.html.
   Run \`node port-figs.mjs --check\` to prove they have not drifted. */
export const FIG = {
${body}
};
`;
}

const figs = extract();

if (process.argv.includes('--check')) {
  const want = render(figs);
  let have = '';
  try { have = readFileSync('figs.js', 'utf8'); } catch { }
  if (want !== have) {
    console.error('✗ figs.js has DRIFTED from hs2-module1. Run: node port-figs.mjs');
    process.exit(1);
  }
  console.log(`✓ all ${Object.keys(figs).length} figures byte-identical to hs2-module1`);
} else {
  writeFileSync('figs.js', render(figs));
  const svg = Object.values(figs).filter(f => f.kind === 'svg').length;
  console.log(`wrote figs.js — ${Object.keys(figs).length} figures (${svg} authored SVG, ${Object.keys(figs).length - svg} raster)`);
}
